-- Generated from server/simulatedAccountRepository.js. Use the migration command for data cutover.
CREATE TABLE IF NOT EXISTS simulated_accounts ("account_id" INTEGER NOT NULL,
"initial_balance" DOUBLE PRECISION,
"unlimited_capital" BOOLEAN,
PRIMARY KEY ("account_id"),
CHECK (account_id = 1));
CREATE TABLE IF NOT EXISTS simulated_orders ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"order_position" INTEGER,
"record_id" TEXT,
"symbol" TEXT,
"interval" TEXT,
"direction" TEXT,
"status" TEXT,
"market_provider" TEXT,
"error" TEXT,
"reason" TEXT,
"last_review_run_id" TEXT,
"margin" DOUBLE PRECISION,
"leverage" DOUBLE PRECISION,
"notional" DOUBLE PRECISION,
"entry" DOUBLE PRECISION,
"entry_fee" DOUBLE PRECISION,
"quantity" DOUBLE PRECISION,
"exit" DOUBLE PRECISION,
"gross" DOUBLE PRECISION,
"fees" DOUBLE PRECISION,
"funding" DOUBLE PRECISION,
"net" DOUBLE PRECISION,
"roi" DOUBLE PRECISION,
"mark_price" DOUBLE PRECISION,
"unrealized" DOUBLE PRECISION,
"liquidation_price" DOUBLE PRECISION,
"held_bars" DOUBLE PRECISION,
"next_time" DOUBLE PRECISION,
"isolated_loss_adjustment" DOUBLE PRECISION,
"automatic" BOOLEAN,
"ambiguous_bar" BOOLEAN,
"created_at" TIMESTAMPTZ,
"entry_at" TIMESTAMPTZ,
"exit_at" TIMESTAMPTZ,
"expires_at" TIMESTAMPTZ,
"mark_at" TIMESTAMPTZ,
PRIMARY KEY ("account_id","order_id"),
FOREIGN KEY (account_id) REFERENCES simulated_accounts(account_id) ON DELETE CASCADE,
CHECK (status IN ('pending','open','closed','expired','cancelled')),
CHECK (direction IN ('OPEN_LONG','OPEN_SHORT')));
CREATE TABLE IF NOT EXISTS simulated_order_plans ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"plan_kind" TEXT NOT NULL,
"entry_rule" TEXT,
"entry_min" DOUBLE PRECISION,
"entry_max" DOUBLE PRECISION,
"stop_loss" DOUBLE PRECISION,
"take_profit" DOUBLE PRECISION,
"valid_for_bars" DOUBLE PRECISION,
"max_hold_bars" DOUBLE PRECISION,
"net_reward_risk" DOUBLE PRECISION,
PRIMARY KEY ("account_id","order_id","plan_kind"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_costs ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"fee_bps" DOUBLE PRECISION,
"slippage_bps" DOUBLE PRECISION,
"funding_bps_per8h" DOUBLE PRECISION,
"notional" DOUBLE PRECISION,
PRIMARY KEY ("account_id","order_id"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_analysis ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"strategy_version" TEXT,
"analysis_engine" TEXT,
"confidence_type" TEXT,
"reason" TEXT,
"risk" TEXT,
"automation_run_id" TEXT,
"confidence" DOUBLE PRECISION,
"data_as_of" TIMESTAMPTZ,
PRIMARY KEY ("account_id","order_id"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_signals ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"symbol" TEXT,
"exchange" TEXT,
"market_provider" TEXT,
"interval" TEXT,
"position_recommendation" TEXT,
"action" TEXT,
"confidence_type" TEXT,
"reason" TEXT,
"risk" TEXT,
"suggestion" TEXT,
"analysis_engine" TEXT,
"confidence" DOUBLE PRECISION,
"recommended_leverage" DOUBLE PRECISION,
"eligible" BOOLEAN,
"data_as_of" TIMESTAMPTZ,
"generated_at" TIMESTAMPTZ,
"first_entry_at" TIMESTAMPTZ,
"expires_at" TIMESTAMPTZ,
PRIMARY KEY ("account_id","order_id"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_scopes ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"interval" TEXT,
"engine" TEXT,
"symbols_text" TEXT,
"limit" DOUBLE PRECISION,
"max_symbols" DOUBLE PRECISION,
"batch_size" DOUBLE PRECISION,
PRIMARY KEY ("account_id","order_id"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_scope_symbols ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"sequence" INTEGER NOT NULL,
"value" TEXT,
PRIMARY KEY ("account_id","order_id","sequence"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_validation_issues ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"source" TEXT NOT NULL,
"sequence" INTEGER NOT NULL,
"value" TEXT,
PRIMARY KEY ("account_id","order_id","source","sequence"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_protection_revisions ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"sequence" INTEGER NOT NULL,
"stop_loss" DOUBLE PRECISION,
"take_profit" DOUBLE PRECISION,
"effective_from" DOUBLE PRECISION,
"at" TIMESTAMPTZ,
PRIMARY KEY ("account_id","order_id","sequence"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_order_reviews ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"sequence" INTEGER NOT NULL,
"engine" TEXT,
"action" TEXT,
"reason" TEXT,
"stop_loss" DOUBLE PRECISION,
"take_profit" DOUBLE PRECISION,
"effective_from" DOUBLE PRECISION,
"confidence" DOUBLE PRECISION,
"at" TIMESTAMPTZ,
"previous_stop_loss" DOUBLE PRECISION,
"previous_take_profit" DOUBLE PRECISION,
PRIMARY KEY ("account_id","order_id","sequence"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_automation_settings ("account_id" INTEGER NOT NULL,
"engine" TEXT,
"interval" TEXT,
"version" DOUBLE PRECISION,
"margin" DOUBLE PRECISION,
"enabled" BOOLEAN,
PRIMARY KEY ("account_id"),
FOREIGN KEY (account_id) REFERENCES simulated_accounts(account_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_automation_jobs ("account_id" INTEGER NOT NULL,
"job_kind" TEXT NOT NULL,
"owner" TEXT,
"run_id" TEXT,
"engine" TEXT,
"index" DOUBLE PRECISION,
"total" DOUBLE PRECISION,
"held" DOUBLE PRECISION,
"failed" DOUBLE PRECISION,
"updated" DOUBLE PRECISION,
"eligible" DOUBLE PRECISION,
"submitted" DOUBLE PRECISION,
"started_at" DOUBLE PRECISION,
"finished_at" DOUBLE PRECISION,
"lease_until" DOUBLE PRECISION,
"next_at" DOUBLE PRECISION,
"running" BOOLEAN,
PRIMARY KEY ("account_id","job_kind"),
FOREIGN KEY (account_id) REFERENCES simulated_accounts(account_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_automation_symbols ("account_id" INTEGER NOT NULL,
"job_kind" TEXT NOT NULL,
"sequence" INTEGER NOT NULL,
"value" TEXT,
PRIMARY KEY ("account_id","job_kind","sequence"),
FOREIGN KEY (account_id) REFERENCES simulated_accounts(account_id) ON DELETE CASCADE,
FOREIGN KEY (account_id, job_kind) REFERENCES simulated_automation_jobs(account_id, job_kind) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_automation_errors ("account_id" INTEGER NOT NULL,
"job_kind" TEXT NOT NULL,
"sequence" INTEGER NOT NULL,
"value" TEXT,
PRIMARY KEY ("account_id","job_kind","sequence"),
FOREIGN KEY (account_id) REFERENCES simulated_accounts(account_id) ON DELETE CASCADE,
FOREIGN KEY (account_id, job_kind) REFERENCES simulated_automation_jobs(account_id, job_kind) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS simulated_account_extensions ("account_id" INTEGER NOT NULL,
"path" TEXT[] NOT NULL,
"value_kind" TEXT,
"text_value" TEXT,
"number_value" DOUBLE PRECISION,
"boolean_value" BOOLEAN,
PRIMARY KEY ("account_id","path"),
FOREIGN KEY (account_id) REFERENCES simulated_accounts(account_id) ON DELETE CASCADE,
CHECK (value_kind IN ('object','array','null','string','number','boolean')));
CREATE TABLE IF NOT EXISTS simulated_order_extensions ("account_id" INTEGER NOT NULL,
"order_id" TEXT NOT NULL,
"path" TEXT[] NOT NULL,
"value_kind" TEXT,
"text_value" TEXT,
"number_value" DOUBLE PRECISION,
"boolean_value" BOOLEAN,
PRIMARY KEY ("account_id","order_id","path"),
FOREIGN KEY (account_id, order_id) REFERENCES simulated_orders(account_id, order_id) ON DELETE CASCADE,
CHECK (value_kind IN ('object','array','null','string','number','boolean')));
CREATE INDEX IF NOT EXISTS simulated_orders_active_idx ON simulated_orders(account_id, next_time) WHERE status IN ('pending','open');
CREATE INDEX IF NOT EXISTS simulated_orders_symbol_idx ON simulated_orders(account_id, symbol, created_at DESC);
CREATE INDEX IF NOT EXISTS simulated_orders_record_idx ON simulated_orders(account_id, record_id, symbol);
CREATE INDEX IF NOT EXISTS simulated_orders_closed_idx ON simulated_orders(account_id, exit_at DESC) WHERE status = 'closed';
CREATE INDEX IF NOT EXISTS simulated_order_analysis_strategy_idx ON simulated_order_analysis(strategy_version, analysis_engine);
CREATE TABLE IF NOT EXISTS simulated_account_migrations (
  version INTEGER PRIMARY KEY, migrated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  source_order_count INTEGER NOT NULL, source_digest TEXT NOT NULL
);
